[profiles]
[profiles.common]
    dotfiles = [ "fish", "neovim", "zathura", "neofetch" ]

[profiles.dwm]
    dotfiles = [ "dwm", "st", "xinitrcDwm" ]

[profiles.sway]
    dotfiles = [ "sway", "mako", "wayland", "alacritty", "waybar" ]


#   ______
#  / ____/___  ____ ___  ____ ___  ____  ____
# / /   / __ \/ __ `__ \/ __ `__ \/ __ \/ __ \
#/ /___/ /_/ / / / / / / / / / / / /_/ / / / /
#\____/\____/_/ /_/ /_/_/ /_/ /_/\____/_/ /_/

    [dotfiles]
    [dotfiles.blender]
        source = "blender"
        target = "~/.config/blender"

    [dotfiles.neofetch]
        source = "neofetch"
        target = "~/.config/neofetch"

    [dotfiles.neovim]
        source = "neovim"
        target = "~/.config/nvim"
        hooks  = [ "nvim +PlugInstall +qall" ]

    [dotfiles.fish]
        source = "fish"
        target = "~/.config/fish"
        hooks  = [ "echo '[ -x /bin/fish ] && SHELL=/bin/fish exec /bin/fish' >> ~/.bashrc" ]

    [dotfiles.zathura]
        source = "zathura"
        target = "~/.config/zathura"

    [dotfiles.wallpaper]
        source = "wallpaper"
        target = "~/.config/wallpaper"

    [dotfiles.scripts]
        source = "scripts"
        target = "~/.local/bin/scripts"
        hooks  = [ "echo 'set -gx PATH ~/.local/bin $PATH'", 
                   "echo 'set -gx PATH ~/.local/bin/scripts $PATH'" ]

# _       __            __                __
#| |     / /___ ___  __/ /___ _____  ____/ /
#| | /| / / __ `/ / / / / __ `/ __ \/ __  /
#| |/ |/ / /_/ / /_/ / / /_/ / / / / /_/ /
#|__/|__/\__,_/\__, /_/\__,_/_/ /_/\__,_/
#             /____/
    [dotfiles.sway]
        source = "sway"
        target = "~/.config/sway"
        hooks  = [ "sway reload" ]

    [dotfiles.waybar]
        source = "waybar"
        target = "~/.config/waybar"
        hooks  = [ "sway reload" ]

    [dotfiles.mako]
        source = "mako"
        target = "~/.config/mako"

    [dotfiles.alacritty]
        source = "alacritty"
        target = "~/.config/alacritty"

    [dotfiles.wayland]
        hooks  = [ """CONF_DIR="$HOME/.config/fish/config.fish"
                      grep -qxF 'set MOZ_ENABLE_WAYLAND 1' $CONF_DIR ||
                      echo 'set MOZ_ENABLE_WAYLAND 1'       >> $CONF_DIR |
                      echo 'set QT_QPA_PLATFORM    wayland' >> $CONF_DIR |
                      echo 'set GDK_BACKEND        wayland' >> $CONF_DIR |
                      echo 'set XDG_SESSION_TYPE   wayland' >> $CONF_DIR""" ]
#   _  __
#  | |/ / ____  _________ _
#  |   / / __ \/ ___/ __ `/
# /   |_/ /_/ / /  / /_/ /
#/_/|_(_)____/_/   \__, /
#                 /____/
    [dotfiles.picom]
        source = "picom"
        target = "~/.config/picom.conf"

#       __
#  ____/ /      ______ ___
# / __  / | /| / / __ `__ \
#/ /_/ /| |/ |/ / / / / / /
#\__,_/ |__/|__/_/ /_/ /_/
    # [dotfiles.dwm]
    #     source =
    #     target =
    #     hooks  =

    # [dotfiles.st]
    #     source =
    #     target =
    #     hooks  =

    # [dotfiles.xinitrcDwm]
    #     source = 
    #     target =
    #     hooks  = [ ]

    # [dotfiles.dwmblocks]
    #     source =
    #     target =
    #     hooks  =
