user = "beshenka"

[profiles]
[profiles.common]
    dotfiles = [ "fish", "neovim", "zathura", "neofetch" ]

[dotfiles.alacritty]
    source = "alacritty"
    target = "~/.config/alacritty"

[dotfiles.neofetch]
    source = "neofetch"
    target = "~/.config/neofetch"

[dotfiles.neovim]
    source = "neovim"
    target = "~/.config/nvim"
    hooks  = [ """sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
                         https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim' """,
               "nvim --headless +PlugInstall +qa" ]

[dotfiles.fish]
    source = "fish"
    target = "~/.config/fish"
    hooks  = [ "echo '[ -x /bin/fish ] && SHELL=/bin/fish exec /bin/fish' >> ~/.bashrc" ]

[dotfiles.zathura]
    source = "zathura"
    target = "~/.config/zathura"

[dotfiles.picom]
    source = "picom"
    target = "~/.config/picom"

[dotfiles.polybar]
    source = "polybar"
    target = "~/.config/polybar/"

[dotfiles.bspwm]
    source = "bspwm"
    target = "~/.config/bspwm/"

[dotfiles.dunst]
    source = "dunst"
    target = "~/.config/dunst"

[dotfiles.rofi]
    source = "rofi"
    target = "~/.config/rofi"

[dotfiles.redshift]
    source = "redshift"
    target = "~/.config/redshift.conf"

[dotfiles.sxhkd]
    source = "sxhkd"
    target = "~/.config/sxhkd/"

[dotfiles.GIMP]
    source = "GIMP"
    target = "~/.config/GIMP"

[dotfiles.Xresources]
    source = "Xresources"
    target = "~/.Xresources"

[dotfiles.zsh]
    source = "zsh"
    target = "~/.zshrc"

[dotfiles.zsh_plugins]
    source = "zsh_plugins"
    target = "~/.zsh_plugins"

[dotfiles.dir_colors]
    source = "dir_colors"
    target = "~/.dir_colors"

[dotfiles.cmus]
    source = "cmus"
    target = "~/.config/cmus"

[dotfiles.xsettingsd]
    source = "xsettingsd"
    target = "~/.config/xsettingsd"

[dotfiles.bin]
    source = "bin"
    target = "~/.local/bin"

[dotfiles.init]
    source = "init"
    target = "~/.config/emacs/init.el"
