#!/bin/sh

start() {
    killall -q $1
    while pgrep -x $1 >/dev/null; do sleep 1; done
    $@ &
}

start dunst
start picom -b --experimental-backends
start xautolock -time 10 -locker '$HOME/.local/bin/lock.sh'
start sxhkd
start flameshot
start redshift-gtk

~/.local/bin/switchtheme.sh d
start ~/.local/bin/changewallpaper.sh d &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config focused_border_color "#88C0D0"
bspc config normal_border_color "#e6eef3"
bspc config active_border_color "#eceff4"
bspc config presel_feedback_color "#98C379"

bspc config border_width         1
bspc config split_ratio          0.5
bspc config window_gap           4

bspc config borderless_monocle   true
bspc config paddingless_monocle  true
bspc config gapless_monocle      true
bspc config single_monocle       true

# control
bspc config focus_follows_pointer   true
bspc config pointer_motion_interval 4
