#!/bin/sh

source $HOME/.config/bspwm/autostart
source $HOME/.config/bspwm/wallpaper

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config focused_border_color  "#dc9656"
bspc config normal_border_color   "#f8f8f8"
bspc config active_border_color   "#f8f8f8"
bspc config presel_feedback_color "#585858"

bspc config border_width         1
bspc config split_ratio          0.5
bspc config window_gap           4

bspc config borderless_monocle   true
bspc config paddingless_monocle  true
bspc config gapless_monocle      true
bspc config single_monocle       true

# control
bspc config focus_follows_pointer   true
bspc config pointer_motion_interval 4
