#!/bin/sh

start() {
    killall -q $1
    while pgrep -x $1 >/dev/null; do sleep 1; done
    $@ &
}

acpi_check() {
	while :; do
		B=$(acpi -b | sed -ne 's/Battery 0.* \([0-9]*\)%.*/\1/p')
		if [ $B -le 15 ]; then
			notify-send "Battery power is lower than 15%!" -u critical
		fi

		sleep 30
	done
}

acpi_check &

start dunst
start picom -b --experimental-backends
start sxhkd

case `cat /sys/class/dmi/id/chassis_type` in
	9 | 10)
		start polybar --config=~/.config/polybar/config.ini laptop ;;
	*)
		start polybar --config=~/.config/polybar/config.ini pc ;;
esac

start flameshot
start xsettingsd
start redshift

killall xautolock
xautolock -time 5 -corners ---- -locker "$HOME/.local/bin/lock" &

# feh --bg-scale ~/.wallpapers/wow_forest.png

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config focused_border_color  "#dc9656"
bspc config normal_border_color   "#f8f8f8"
bspc config active_border_color   "#f8f8f8"
bspc config presel_feedback_color "#585858"

bspc config border_width         1
bspc config split_ratio          0.5
bspc config window_gap           4

bspc config borderless_monocle   true
bspc config paddingless_monocle  true
bspc config gapless_monocle      true
bspc config single_monocle       true

# control
bspc config focus_follows_pointer   true
bspc config pointer_motion_interval 4
